(() => {
  "use strict";
  const cfg=window.MALLA_CONFIG||{}, api=window.MALLA_V4;
  if(!api)return;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const GUEST_KEY="mallaPUCV_v32_guest";
  let supa=null,user=null,profile=null,isAdmin=false,cloudReady=false,cloudApplying=false,pushTimer=null;
  const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':'&quot;'}[c]));
  const norm=v=>String(v||"").toUpperCase().replace(/\s+/g,"").trim();
  const toast=t=>api.toast?.(t);

  function modal(title,html){$("#modalGeneralTitulo").textContent=title;$("#modalGeneralContenido").innerHTML=html;$("#modalGeneral").hidden=false;}
  function buildAuth(){
    const d=document.createElement("div");d.id="stableAuth";d.className="stable-auth";d.innerHTML=`<section class="stable-auth-card"><p class="eyebrow">Malla interactiva · PUCV</p><h2>Pedagogía en Inglés</h2><p>Guarda tu progreso en este dispositivo o inicia sesión para sincronizarlo entre tus equipos.</p><button class="stable-google" id="stableGoogle">Continuar con Google</button><div class="stable-auth-grid"><input id="stableEmail" type="email" autocomplete="email" placeholder="Email"><input id="stablePassword" type="password" autocomplete="current-password" placeholder="Contraseña · mínimo 6 caracteres"></div><div class="stable-auth-actions"><button class="btn" id="stableLogin">Iniciar sesión</button><button class="btn secundario" id="stableSignup">Crear cuenta</button></div><div class="stable-auth-message" id="stableAuthMessage"></div><button class="stable-guest" id="stableGuest">Continuar como invitada</button></section>`;document.body.prepend(d);
    $("#stableGoogle").onclick=loginGoogle;$("#stableLogin").onclick=()=>emailAuth(false);$("#stableSignup").onclick=()=>emailAuth(true);$("#stableGuest").onclick=()=>enterGuest(true);
  }
  const authMsg=t=>{$("#stableAuthMessage").textContent=t||""};
  const showAuth=()=>{$("#stableAuth").hidden=false}; const hideAuth=()=>{$("#stableAuth").hidden=true};

  async function init(){
    buildAuth();
    if(cfg.authEnabled!==false&&cfg.supabaseUrl&&cfg.supabasePublishableKey&&window.supabase){
      supa=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
      const {data:{session}}=await supa.auth.getSession();
      if(session?.user)await enterUser(session.user); else if(localStorage.getItem(GUEST_KEY)==="1")enterGuest(false); else showAuth();
      supa.auth.onAuthStateChange(async(event,session)=>{if(session?.user&&session.user.id!==user?.id)await enterUser(session.user);if(event==="SIGNED_OUT"){user=null;profile=null;cloudReady=false;updateIdentity();showAuth();}});
    } else enterGuest(false);
    $("#accountBtn")?.addEventListener("click",openProfile);
    $("#feedbackLink")?.addEventListener("click",e=>{e.preventDefault();openFeedback();});
    window.addEventListener("malla:datachange",schedulePush);window.addEventListener("online",schedulePush);
  }
  async function loginGoogle(){if(!supa)return authMsg("Supabase no está conectado.");authMsg("Abriendo Google…");const {error}=await supa.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}${location.pathname}`}});if(error)authMsg(error.message);}
  async function emailAuth(signup){if(!supa)return authMsg("Supabase no está conectado.");const email=$("#stableEmail").value.trim(),password=$("#stablePassword").value;if(!email||password.length<6)return authMsg("Escribe un correo válido y una contraseña de al menos 6 caracteres.");authMsg(signup?"Creando cuenta…":"Iniciando sesión…");const res=signup?await supa.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}${location.pathname}`}}):await supa.auth.signInWithPassword({email,password});if(res.error)return authMsg(res.error.message);if(signup&&!res.data.session)authMsg("Cuenta creada. Revisa tu correo para confirmar.");else if(res.data.user)await enterUser(res.data.user);}
  function enterGuest(save){if(save)localStorage.setItem(GUEST_KEY,"1");user=null;profile=null;cloudReady=false;hideAuth();updateIdentity();}
  async function enterUser(u){user=u;localStorage.removeItem(GUEST_KEY);hideAuth();const {data:p}=await supa.from("profiles").select("*").eq("id",u.id).maybeSingle();profile=p||null;try{const {data:a}=await supa.from("app_admins").select("user_id").eq("user_id",u.id).maybeSingle();isAdmin=Boolean(a);}catch{}await reconcileCloud();updateIdentity();}
  function updateIdentity(){const name=profile?.display_name||user?.user_metadata?.full_name||user?.email?.split("@")[0]||"Invitada",av=profile?.avatar_url||user?.user_metadata?.avatar_url||user?.user_metadata?.picture;$("#accountName").textContent=name;const a=$("#accountAvatar");a.innerHTML="";if(av){const img=document.createElement("img");img.src=av;img.alt="";a.append(img)}else a.textContent=name.slice(0,1).toUpperCase();}
  function meaningful(d){return Object.values(d.courses||{}).some(c=>c.state!=="none"||c.planned||c.grade||c.note||(c.assessments||[]).length||Number(c.attendance?.total)||c.history?.year)||(d.customCourses||[]).length||Boolean(d.preferences?.minor)}
  async function reconcileCloud(){if(!supa||!user)return;const [{data:rows},{data:custom},{data:settings}]=await Promise.all([supa.from("course_progress").select("*"),supa.from("custom_courses").select("*"),supa.from("user_settings").select("settings").eq("user_id",user.id).maybeSingle()]);const st=settings?.settings||{},has=(rows?.length||0)>0||(custom?.length||0)>0||Object.keys(st).length>0;if(has){applyCloud(rows||[],custom||[],st);toast("Progreso sincronizado");}else if(meaningful(api.getData())){await pushCloud();toast("Tu progreso local se guardó en tu cuenta");}cloudReady=true;}
  function applyCloud(rows,custom,settings){cloudApplying=true;const d=api.defaultData();rows.forEach(r=>{d.courses[r.course_id]={state:r.status==="approved"?"approved":r.status==="current"?"inprogress":"none",planned:r.status==="planned",grade:r.grade??"",note:r.note??""};});custom.forEach(c=>{const uid=`custom-${norm(c.code)}`;d.courses[uid]={state:c.status==="approved"?"approved":c.status==="current"?"inprogress":"none",planned:c.status==="planned",grade:c.grade??"",note:c.note??""};d.customCourses.push({uid,code:c.code,name:c.name,credits:Number(c.credits||0),semester:String(c.semester),type:c.category==="optative"?"optativo":c.category==="fofu"?"fofu":"otro",slot:c.reference_slot||"",minorIds:Array.isArray(c.minor_names)?c.minor_names:[],source:c.source||"manual"});});d.preferences={...d.preferences,...(settings.preferences||settings||{})};const extras=settings.courseExtras||{};Object.entries(extras).forEach(([id,x])=>{d.courses[id]={...(d.courses[id]||{}),assessments:x.assessments||[],attendance:x.attendance||{},history:x.history||{}}});if(profile){if(profile.current_semester)d.preferences.currentSemester=String(profile.current_semester);if(profile.selected_minor!=null)d.preferences.minor=profile.selected_minor||"";if(profile.theme)d.preferences.theme=profile.theme;d.preferences.view=profile.compact_view?"compact":"normal";}api.importData(d);setTimeout(()=>cloudApplying=false,80);}
  const dbState=c=>c?.state==="approved"?"approved":c?.state==="inprogress"?"current":c?.planned?"planned":"available";
  async function pushCloud(){if(!supa||!user||cloudApplying)return;const d=api.getData(),baseIds=new Set($$(".ramo:not([data-custom='1'])").map(r=>r.dataset.id));const base=[...baseIds].map(id=>{const c=d.courses?.[id]||{};return{user_id:user.id,course_id:id,status:dbState(c),grade:c.grade===""||c.grade==null?null:Number(c.grade),note:c.note||null}});const custom=(d.customCourses||[]).map(c=>{const x=d.courses?.[c.uid]||{};return{user_id:user.id,code:c.code,name:c.name,credits:Number(c.credits||0),semester:Number(c.semester),category:c.type==="optativo"?"optative":c.type,status:dbState(x),grade:x.grade===""||x.grade==null?null:Number(x.grade),note:x.note||null,reference_slot:c.slot||null,source:c.source==="minor"?"minor":"manual",minor_names:c.minorIds||[]}});const extras={};Object.entries(d.courses||{}).forEach(([id,c])=>{if((c.assessments||[]).length||Number(c.attendance?.total)||c.attendance?.minimum!==""||c.history?.year)extras[id]={assessments:c.assessments||[],attendance:c.attendance||{},history:c.history||{}}});try{await supa.from("course_progress").upsert(base,{onConflict:"user_id,course_id"});await supa.from("custom_courses").delete().eq("user_id",user.id);if(custom.length)await supa.from("custom_courses").insert(custom);const pref=d.preferences||{};await supa.from("profiles").update({current_semester:pref.currentSemester==="auto"?null:Number(pref.currentSemester),selected_minor:pref.minor||null,theme:pref.theme||"light",compact_view:pref.view==="compact"}).eq("id",user.id);await supa.from("user_settings").upsert({user_id:user.id,settings:{preferences:pref,courseExtras:extras}},{onConflict:"user_id"});}catch(e){console.warn(e);toast("No pude sincronizar algunos cambios");}}
  function schedulePush(){if(!user||!cloudReady||cloudApplying)return;clearTimeout(pushTimer);pushTimer=setTimeout(pushCloud,700);}
  function openProfile(){const name=profile?.display_name||user?.user_metadata?.full_name||user?.email||"Invitada";modal("Cuenta y perfil",`<div class="profile-card"><div class="profile-line"><div><strong>${esc(name)}</strong><small>${user?esc(user.email||"Cuenta conectada"):"Guardado solo en este dispositivo"}</small></div><span>${user?"Sincronizada":"Local"}</span></div>${user?'<button class="btn secundario" id="stableSyncNow">Sincronizar ahora</button>'+(isAdmin?'<button class="btn secundario" id="stableInbox">Sugerencias recibidas</button>':'')+'<button class="btn peligro-suave" id="stableSignout">Cerrar sesión</button>':'<button class="btn" id="stableShowLogin">Iniciar sesión / crear cuenta</button>'}</div>`);$("#stableSyncNow")?.addEventListener("click",pushCloud);$("#stableInbox")?.addEventListener("click",openInbox);$("#stableSignout")?.addEventListener("click",()=>supa?.auth.signOut());$("#stableShowLogin")?.addEventListener("click",()=>{$("#modalGeneral").hidden=true;showAuth();});}

  async function openInbox(){if(!supa||!isAdmin)return;const {data,error}=await supa.from("feedback").select("*").order("created_at",{ascending:false}).limit(100);if(error){toast("No pude abrir las sugerencias");return;}modal("Sugerencias recibidas",`<div class="general-list">${(data||[]).length?(data||[]).map(x=>`<div class="general-item"><strong>${esc(x.title)} · ${esc(x.type)}</strong><span>${esc(x.message)}</span><small>${new Date(x.created_at).toLocaleString("es-CL")}${x.contact?` · ${esc(x.contact)}`:""}</small></div>`).join(""):"<p>Aún no hay sugerencias.</p>"}</div>`);}
  function openFeedback(){modal("Sugerencias",`<form class="feedback-form" id="feedbackForm"><label>Tipo<select id="feedbackType"><option value="idea">Idea</option><option value="bug">Error</option><option value="confusing">Algo confuso</option><option value="data">Dato incorrecto</option><option value="other">Otro</option></select></label><label>Cuéntame<input id="feedbackTitle" maxlength="100" placeholder="Resumen corto" required><textarea id="feedbackBody" rows="5" maxlength="1500" placeholder="¿Qué cambiarías o qué pasó?" required></textarea></label><label>Contacto opcional<input id="feedbackContact" maxlength="160" placeholder="Instagram, correo, etc."></label><button class="btn" type="submit">Enviar</button><p class="detalle-faltantes">Si la bandeja de sugerencias aún no está activada en Supabase, quedará guardada localmente para no perderla.</p></form>`);$("#feedbackForm").addEventListener("submit",sendFeedback);}
  async function sendFeedback(e){e.preventDefault();const item={type:$("#feedbackType").value,title:$("#feedbackTitle").value.trim(),message:$("#feedbackBody").value.trim(),contact:$("#feedbackContact").value.trim()||null,page_version:"3.2.0"};if(supa){const payload={...item,user_id:user?.id||null};const {error}=await supa.from("feedback").insert(payload);if(!error){$("#modalGeneral").hidden=true;toast("Sugerencia enviada. Gracias ♡");return;}}const pending=JSON.parse(localStorage.getItem("mallaPUCV_feedback_pending")||"[]");pending.push({...item,created_at:new Date().toISOString()});localStorage.setItem("mallaPUCV_feedback_pending",JSON.stringify(pending));$("#modalGeneral").hidden=true;toast("Sugerencia guardada en este dispositivo");}
  init();
})();
